-- =============================================================
-- Supabase Migration: ShopProject SQLite → PostgreSQL
-- Generated: 2026-04-02
-- Run this in: Supabase Dashboard → SQL Editor
-- =============================================================

-- Drop tables in reverse dependency order (safe re-run)
DROP TABLE IF EXISTS order_predictions CASCADE;
DROP TABLE IF EXISTS product_reviews   CASCADE;
DROP TABLE IF EXISTS order_items       CASCADE;
DROP TABLE IF EXISTS shipments         CASCADE;
DROP TABLE IF EXISTS orders            CASCADE;
DROP TABLE IF EXISTS products          CASCADE;
DROP TABLE IF EXISTS customers         CASCADE;

-- ----------------------------------------------------------------
-- customers
-- ----------------------------------------------------------------
CREATE TABLE customers (
  customer_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name        TEXT        NOT NULL,
  email            TEXT        NOT NULL UNIQUE,
  gender           TEXT        NOT NULL,   -- 'Male', 'Female', 'Non-binary'
  birthdate        DATE        NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL,
  city             TEXT,
  state            TEXT,
  zip_code         TEXT,
  customer_segment TEXT,                   -- 'budget', 'standard', 'premium'
  loyalty_tier     TEXT,                   -- 'none', 'silver', 'gold'
  is_active        BOOLEAN     NOT NULL DEFAULT TRUE
);

-- ----------------------------------------------------------------
-- products
-- ----------------------------------------------------------------
CREATE TABLE products (
  product_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku          TEXT           NOT NULL UNIQUE,
  product_name TEXT           NOT NULL,
  category     TEXT           NOT NULL,
  price        NUMERIC(10,2)  NOT NULL,
  cost         NUMERIC(10,2)  NOT NULL,
  is_active    BOOLEAN        NOT NULL DEFAULT TRUE
);

-- ----------------------------------------------------------------
-- orders
-- ----------------------------------------------------------------
CREATE TABLE orders (
  order_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     BIGINT         NOT NULL REFERENCES customers(customer_id),
  order_datetime  TIMESTAMPTZ    NOT NULL,
  billing_zip     TEXT,
  shipping_zip    TEXT,
  shipping_state  TEXT,
  payment_method  TEXT           NOT NULL,   -- 'card', 'paypal', 'bank', 'crypto'
  device_type     TEXT           NOT NULL,   -- 'mobile', 'desktop', 'tablet'
  ip_country      TEXT           NOT NULL,
  promo_used      BOOLEAN        NOT NULL DEFAULT FALSE,
  promo_code      TEXT,
  order_subtotal  NUMERIC(10,2)  NOT NULL,
  shipping_fee    NUMERIC(10,2)  NOT NULL,
  tax_amount      NUMERIC(10,2)  NOT NULL,
  order_total     NUMERIC(10,2)  NOT NULL,
  risk_score      NUMERIC(5,2)   NOT NULL,
  is_fraud        BOOLEAN        NOT NULL DEFAULT FALSE
);

-- ----------------------------------------------------------------
-- order_items
-- ----------------------------------------------------------------
CREATE TABLE order_items (
  order_item_id  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id       BIGINT          NOT NULL REFERENCES orders(order_id),
  product_id     BIGINT          NOT NULL REFERENCES products(product_id),
  quantity       INTEGER         NOT NULL,
  unit_price     NUMERIC(10,2)   NOT NULL,
  line_total     NUMERIC(10,2)   NOT NULL
);

-- ----------------------------------------------------------------
-- shipments
-- ----------------------------------------------------------------
CREATE TABLE shipments (
  shipment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        BIGINT       NOT NULL UNIQUE REFERENCES orders(order_id),
  ship_datetime   TIMESTAMPTZ  NOT NULL,
  carrier         TEXT         NOT NULL,   -- 'UPS', 'FedEx', 'USPS'
  shipping_method TEXT         NOT NULL,   -- 'standard', 'expedited', 'overnight'
  distance_band   TEXT         NOT NULL,   -- 'local', 'regional', 'national'
  promised_days   INTEGER      NOT NULL,
  actual_days     INTEGER      NOT NULL,
  late_delivery   BOOLEAN      NOT NULL DEFAULT FALSE
);

-- ----------------------------------------------------------------
-- product_reviews
-- ----------------------------------------------------------------
CREATE TABLE product_reviews (
  review_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     BIGINT       NOT NULL REFERENCES customers(customer_id),
  product_id      BIGINT       NOT NULL REFERENCES products(product_id),
  rating          INTEGER      NOT NULL CHECK (rating BETWEEN 1 AND 5),
  review_datetime TIMESTAMPTZ  NOT NULL,
  review_text     TEXT,
  UNIQUE (customer_id, product_id)
);

-- ----------------------------------------------------------------
-- order_predictions
-- ----------------------------------------------------------------
CREATE TABLE order_predictions (
  order_id                   BIGINT  PRIMARY KEY REFERENCES orders(order_id),
  late_delivery_probability  REAL,
  predicted_late_delivery    BOOLEAN,
  prediction_timestamp       TIMESTAMPTZ
);
